### ISSUE TITLE
THhe program crashes after a few seconds

### ISSUE THREAD

**Issue by finnishhacker** [Pirate-Crew/IPTV-Sharp#2]
Hi, i try to run this. put the website and its port but the program crashes after a little while. any thoughts why it does that?

**Comment by barukai** [comment]
Anche a me si presenta lo stesso problema. Ho Windows 10.
Grazie comunque per il contributo

**Comment by finnishhacker** [comment]
Io ho Windows 7

**Comment by Delfioh** [comment]
All the pointed out issues should be fixed by now, feel free to compile from the updated sources or wait till a new compiled release is out. 

I problemi segnalati dovrebbero essere stati eliminati, potete tranquillamente compilare dai sorgenti aggiornati o aspettare che arrivi la nuova release già compilata
